[T-core]
name = "Core"
ping = "rust-lang/core"
members = [
  "alexcrichton",
  "ashleygwilliams",
  "aturon",
  "carols10cents",
  "nikomatsakis",
  "nrc",
  "steveklabnik",
  "wycats",
]

[T-lang]
name = "Language"
ping = "rust-lang/lang"
members = [
  "aturon",
  "cramertj",
  "eddyb",
  "nikomatsakis",
  "nrc",
  "pnkfelix",
  "withoutboats",
]

[T-libs]
name = "Libraries"
ping = "rust-lang/libs"
members = [
  "alexcrichton",
  "aturon",
  "BurntSushi",
  "dtolnay",
  "Kimundi",
  "sfackler",
]

[T-compiler]
name = "Compiler"
ping = "rust-lang/compiler"
members = [
  "arielb1",
  "cramertj",
  "eddyb",
  "estebank",
  "jseyfried",
  "michaelwoerister",
  "nikomatsakis",
  "nrc",
  "petrochenkov",
  "pnkfelix",
  "Zoxc",
]

[T-doc]
name = "Documentation"
ping = "rust-lang/docs"
members = [
  "frewsxcv",
  "GuillaumeGomez",
  "QuietMisdreavus",
  "steveklabnik",
]

[T-infra]
name = "Infrastructure"
ping = "rust-lang/infra"
members = [
  "aidanhs",
  "alexcrichton",
  "aturon",
  "carols10cents",
  "erickt",
  "kennytm",
  "Mark-Simulacrum",
  "shepmaster",
  "TimNN",
]

[T-cargo]
name = "Cargo"
ping = "rust-lang/cargo"
members = [
  "alexcrichton",
  "aturon",
  "carols10cents",
  "joshtriplett",
  "matklad",
  "withoutboats",
  "wycats",
]

[T-dev-tools]
name = "Dev tools"
ping = "rust-lang/dev-tools"
members = [
  "fitzgen",
  "japaric",
  "jonathandturner",
  "killercup",
  "matklad",
  "michaelwoerister",
  "nrc",
]
